import Footer from "@/components/Cup";
import Footers from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Cofe Shop",
  description: "Generated by Cofe Shop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footers/>
        </body>
    </html>
  );
}
